tryber/sd-013-b-project-frontend-online-store

src/services/api.js
https://trello.com/c/RYKa3wtT/20-req-01-implemente-o-módulo-que-acessa-a-api-do-mercado-livre
=> Requisito 1

src/App.js, src/Components/BarSearch.jsx, src/Components/RenderApp.jsx
https://trello.com/c/62o5cKSt/1-req-02-criar-o-campo-de-busca-da-tela-principal-a-listagem-de-produtos-inicialmente-vazia
=> Concluindo Requisito 2

.gitignore, src/services/api.js
https://trello.com/c/RYKa3wtT/20-req-01-implemente-o-módulo-que-acessa-a-api-do-mercado-livre
=> [ Grupo 16 ] concluir requisito 1

src/App.js, src/Pages/Initial.js, src/Pages/ShoppingCart.js
https://trello.com/c/3wXSBqvE/2-req-03-criar-o-bot%C3%A3o-de-carrinho-de-compras-na-tela-principal
=> [Group 5] Requisito 3

package-lock.json, package.json, src/App.js, src/components/initial/Home.jsx, src/components/initial/ShoppingCart.jsx
Adicionando requisito 03, e adicionando biblioteca React-Icons
=> Requisito 03  Grupo 12

README.md, src/services/api.js
https://trello.com/c/UqbYSLEA/20-req-01-implemente-o-m%C3%B3dulo-que-acessa-a-api-do-mercado-livre
=> [Grupo 33] Requisito 1

src/App.js, src/SearchBar.jsx
https://trello.com/c/FBihvNvT/1-req-02-criar-o-campo-de-busca-da-tela-principal-a-listagem-de-produtos-inicialmente-vazia
=> [Grupo 21] Requisito 2 - Implementação da Search Bar

src/Pages/Initial.js
https://trello.com/c/AZfucbbS/3-req-04-listar-filtros-de-categoria-obtidos-da-api-na-tela-principal-de-listagem-do-produto
=> [Group 5] Requisito 4

package-lock.json, src/services/api.js
=> [Main group 25] get products

package-lock.json, src/App.js, src/SearchBar.jsx, src/ShoppingCart.jsx
https://trello.com/c/W75vZdf7/2-req-03-criar-o-bot%C3%A3o-de-carrinho-de-compras-na-tela-principal
=> [Grupo 21] Requisito 3 - Implementação da Página do carrinho de compras

src/Components/Header.js, src/Pages/Initial.js, src/Pages/initial.css
https://trello.com/c/78mgB01P/4-req-05-criar-a-listagem-de-produtos
=> [Group 5] Requisito 5

src/App.js, src/pages/Cart.js, src/pages/ProductList.js
O botão do carrinho teve que ser feito no App.js para passar no avaliador.
=> [Grupo 3] Botão do carrinho

package-lock.json, package.json, src/App.js, src/components/Home.jsx, src/components/ShoppingCart.jsx, src/services/api.js
Requisito 3 e refatoração do requisito 2
=> requisito 3 e refatoraçao do requisito 2

src/App.js, src/Category.jsx, src/SearchBar.jsx, src/ShoppingCart.jsx
https://trello.com/c/3ThlaBGN/3-req-04-listar-filtros-de-categoria-obtidos-da-api-na-tela-principal-de-listagem-do-produto
=> [Grupo 21] Requisito 3 e 4 - Implementação de exibição das categorias

package-lock.json, package.json, src/App.js, src/components/Cart.jsx, src/components/Home.jsx
=> [Main group 25] - requisito 3

src/App.js, src/components/ListItems.jsx, src/components/Main.jsx, src/components/SearchBar.jsx
Todo grupo resolveu o requisito 5.
=> [Grupo Junto- Rebourne] Resolve requisito 5

src/App.css, src/components/CategoryFilter.jsx, src/pages/ProductList.js
Requisito 6 finalizado com muito amor e esforço.
=> [Group 13] Challenge 6 completed

src/App.js, src/components/Home.jsx, src/components/ProductList.jsx
Da uma olhada galera, acredito que ta funcionando bem.
Vo mandar pra codereview no Trello
=> Requisito 5 funcionando

src/pages/ProductsList.js
Corrige bur no texto: Nenhum produto encontrado
=> [Grupo 24] Correção de bug

package-lock.json, src/Components/CategoryList.jsx
component improvement
tirando a declaração da função do constructor
=> Grupo 24 component improvement

src/App.css, src/App.js, src/components/CategoryFilter.js, src/components/ProductCard.js, src/pages/ProductDetails.js, src/pages/ProductList.js, src/pages/ShoppingCart.js
Requisito 7 feito com muito esforço e amor.
=> [Group 13] Challenge 7 completed!

src/App.js, src/components/ProductDetails.jsx, src/components/RenderCard.jsx
https://trello.com/c/hdkRXutm/5-req-07-redirecione-para-uma-tela-com-a-exibi%C3%A7%C3%A3o-detalhada-do-um-produto-clicado
=> [Grupo 21] Requisito 7 Implemetação da Página dos Detalhes do Produto

src/components/ProductDetails.jsx, src/components/ShoppingCart.jsx
https://trello.com/c/fXq9s4UL/22-req-09-permitir-adicionar-o-produto-ao-carrinho-a-partir-da-tela-de-exibi%C3%A7%C3%A3o-detalhada
=> [Grupo 21] Requisito 09

src/App.js, src/Components/Cart.jsx, src/Components/Home.jsx
=> [Grupo8] Squad8 José Breno frontend online store requisito 3

src/components/Home.js, src/components/ProductList.js
Requisito 5 (Requisito passou no teste, porém precisamos rever a lógica para exibição da mensagem "Nenhum produto encontrado" pois a página já inicia renderizando essa mensagem.
=> Requisito 5

src/App.js, src/components/Card.js, src/components/CardList.js, src/components/CartIcon.js, src/pages/Home.js, src/pages/ProductDetails.js
falta adicionar dois data-testid na pagina do carrinho
=> [Grupo 1] requisito 8 - implementa botão de adicionar ao carrinho pela lista

src/App.js, src/pages/ProductDetails.js
Falta os intens ligados à página do carrinho
=> [Grupo 1] Requisito 9 - implementa botão de adicionar ao carrinho na pag ProductDetails

src/App.js, src/Components/CartButton.jsx, src/Components/CategoriesList.jsx, src/Components/ProductCard.jsx, src/Components/ProductInvalid.jsx, src/Components/SearchBar.jsx, src/services/api.js
=> Main group 2 requisito 5

src/App.css, src/App.js, src/components/MainProductList.js, src/components/ProductCard.js, src/components/ShoppingCartCards.js, src/pages/ProductDetails.js, src/pages/ProductList.js, src/pages/ShoppingCart.js, src/services/api.js
Requisito 9 finalizado com muito amor e carinho!
=> [Group - 13] Challenge 9 completed

src/components/AllAssessments.jsx, src/components/FormAssessment.jsx, src/components/ProductDetails.jsx
https://trello.com/c/gQG33LXY/7-req-11-adicionar-formul%C3%A1rio-para-avaliar-e-comentar-acerca-de-um-produto-em-sua-tela-de-exibi%C3%A7%C3%A3o-detalhada
=> [Grupo 21] - Implementação de Avaliações e Comentários na página de Detalhes do Produto

src/App.js, src/components/CartForm.jsx, src/components/CheckoutPage.jsx, src/components/ProductInCart.jsx, src/components/ShoppingCart.jsx
https://trello.com/c/37ZKJTDs/9-req-12-implementar-tela-para-a-finaliza%C3%A7%C3%A3o-da-compra
=> [Grupo 21] Requisito 12 - Criação da página de checkout

src/App.js, src/Components/CategoriesList.jsx, src/Components/ProductCard.jsx, src/Components/ProductList.jsx, src/Components/SearchBar.jsx
=> [Grupo 2] Requisito 6

src/App.js, src/components/ProductCard.jsx, src/components/ProductDetail.jsx, src/services/api.js
=> [Grupo 25] Requisito 7

src/components/Cart.jsx, src/components/Home.jsx, src/components/ProductCard.jsx, src/components/ProductList.jsx, src/components/SearchField.jsx, src/services/api.js
=> [Main group 25] requisito 8 amos

src/Components/Cart.jsx, src/Components/ComponentRadio.jsx, src/Components/Home.jsx, src/Components/ProductDetails.jsx, src/Components/ProductList.jsx
https://trello.com/c/GGLHXTfM/13-req-15-mostrar-quais-produtos-tem-o-frete-grátis
=> [ Main group 16 ] requirement 15

src/App.css, src/components/ProductCard.jsx, src/pages/ProductDetails.jsx
Refatoração do ProductCard.jsx e ProductList.jsx
=> refatoração

src/components/ProductList.jsx, src/components/ShoppingCart.jsx, src/components/ShoppingCartCard.jsx
=> main-group-34 Requisito 8 

src/App.js, src/components/ShoppingCartCards.js, src/pages/ShoppingCart.js
Requisito 10 finalizado with success
=> [Group 13] Challenge 10 completed

src/App.js, src/Components/Card.jsx, src/Pages/Cart.jsx
=> Main group 28 requisito 14

src/components/RenderCard.jsx
https://trello.com/c/PtzM7zTc/13-req-15-mostrar-quais-produtos-tem-o-frete-gr%C3%A1tis
=> [Grupo 21] Verificação dos Itens com Frete grátis

src/components/ProductDetails.jsx, src/components/ProductList.jsx, src/components/ShoppingCart.jsx, src/components/ShoppingCartCard.jsx
=> main-group-34 requisito 09

src/App.css, src/App.js, src/components/CategoriesAside.js, src/components/Home.js, src/components/RenderProducts.js, src/components/SearchBar.js, src/components/ShoppingCart.js, src/services/api.js
Desenvolvido com ajuda de Jose Luis Demeneghi e Matteus Fernandes
=> {Ricardo} Desenvolvimento do Projeto Grupo 18 

src/components/ProductDetail.jsx
=> [Grupo 25] Requisito 9

src/components/CardDetails.js, src/components/Comment.jsx, src/components/FormComment.jsx
https://trello.com/c/UV4T6AkS/7-req-11-adicionar-formul%C3%A1rio-para-avaliar-e-comentar-acerca-de-um-produto-em-sua-tela-de-exibi%C3%A7%C3%A3o-detalhada
=> Main group 33 add form comment req 11

src/components/initial/Home.jsx, src/components/initial/ProductDetails.jsx
Adicionado contador para produtos no carrinho.
=> [Grupo 12] RQ 13 - Adicionado contador para produtos no carrinho.

src/Components/Avaliate.jsx, src/Components/AvaliationsArea.jsx, src/Components/BarSearch.jsx, src/Components/Cart.jsx, src/Components/FormProduct.jsx, src/Components/Home.jsx, src/Components/ProductDetails.jsx, src/Components/ProductList.jsx
https://trello.com/c/hHFq9RL4/7-req-11-adicionar-formulário-para-avaliar-e-comentar-acerca-de-um-produto-em-sua-tela-de-exibição-detalhada
=> [Main group 16] requisito 11 functional e correções

src/components/ProductDetails.jsx, src/components/RenderCard.jsx, src/components/SearchBar.jsx
https://trello.com/c/GDxjFvmv/10-req-13-em-todas-as-telas-com-o-%C3%ADcone-do-carrinho-adicionar-um-n%C3%BAmero-com-a-quantidade-de-produtos-adicionados
=> [Grupo 21] Requisito 13

src/components/RenderCard.jsx
https://trello.com/c/PtzM7zTc/13-req-15-mostrar-quais-produtos-tem-o-frete-gr%C3%A1tis
=> [Grupo 21] Requisito 15

src/components/CardDetails.js, src/components/CardItems.jsx
https://trello.com/c/eJ2gTmut/13-req-15-mostrar-quais-produtos-tem-o-frete-gr%C3%A1tis
=> add req 15 frete gratis

src/components/Cart.jsx, src/components/Home.jsx, src/components/ProductDetail.jsx, src/components/ProductList.jsx
Realização da refatoração das requisições para os detalhes do produto e carrinho.
=> [Main group 25] requisito 10 amos refatorado

src/components/Cart.jsx, src/components/Home.jsx, src/components/ProductDetail.jsx, src/components/ProductList.jsx
Refatora mensagens de busca e produtos não encontrados, implementa requisito 11.
=> [main-group-25] - requisito-11-amos

src/App.js, src/components/Cart.jsx, src/components/CheckoutButton.jsx, src/components/CheckoutForm.jsx, src/components/CheckoutPage.jsx, src/components/CheckoutPayment.jsx
=> Requisito 12

src/components/Cart.jsx, src/components/Home.jsx, src/components/InfoCart.jsx, src/components/ProductCard.jsx, src/components/ProductDetail.jsx, src/components/ProductList.jsx, src/services/api.js
Realiza implementação dos requisitos 13 e 15.
=> [Main group 25] requisitos 13 15 amos

src/App.js, src/components/Cart.jsx, src/components/CheckoutProducts.jsx, src/components/ProductCard.jsx, src/components/ProductDetail.jsx
Finaliza implementação do requisito 12
=> [Main group 25] requisito 12 amos

src/components/Cart.jsx, src/components/ProductCard.jsx, src/components/ProductDetail.jsx
Finaliza implementação do requisito 14
=> [Main group 25] requisito 14 amos

.gitignore, package-lock.json, package.json, src/App.css, src/App.js, src/Components/CartButton.jsx, src/Components/CategoriesList.jsx, src/Components/ProductCard.jsx, src/Components/ProductList.jsx, src/Components/ProductsLibrary.jsx, src/Components/SearchBar.jsx, src/Pages/ShoppingCart.jsx
Estilização do FrontEnd Online Store
=> [Main Group DevSer - 2] Style

src/components/CheckoutForm.jsx, src/components/ProductDetails.jsx, src/components/SearchBar.jsx, src/components/ShoppingCart.jsx
Cria um console.log com descrição para cada página.
Todas adições e subtrações alteram o localStore.
=> refatora bugs na lista de produtos e otimiza o localStora

src/components/CheckoutForm.jsx, src/components/ProductDetails.jsx
Garante que quando alguém comentar sobre o produto esse comentário fica salvo no localStorage.
Limita o número de decimais no preço total do CheckForm.
=> Main group 6 refatora minor bugs

src/components/CartItems.jsx
https://trello.com/c/XbHbPBma/12-req-14-limitar-a-quantidade-de-produtos-adicionados-ao-carrinho-pela-quantidade-dispon%C3%ADvel-em-estoque
=> requisito14

.gitignore, package-lock.json, package.json, src/App.css, src/Components/CartButton.jsx, src/Components/CategoriesList.jsx, src/Components/SearchBar.jsx, src/Pages/ProductsLibrary.jsx
=> [Main Group 2 - DevSer ] New style

src/App.css, src/App.js, src/Components/ProductCard.jsx, src/Components/ProductsList.jsx, src/Components/SearchBar.jsx, src/pages/Cart.jsx, src/pages/Home.jsx, src/pages/ProductDetails.jsx
Comitão bomba: alteração da lógica para o elemento cart, melhorias, limpeza do código, início da estilização CSS, requisito 8 atendido mas não passa no teste, lint OK.
=> Main Group 8 - Início Requisito 8
